### ISSUE TITLE
Vault lookup - Add cache

### ISSUE THREAD

**Issue by apentori** [status-im/infra-template#13]
In order to make the lookup plugin faster, it could be cool to add a cache to store the secret object during the playbook execution in order to reduce the number of call to vault.

**Comment by jakubgs** [comment]
The cache wold obviously have to be encrypted, for example with GPG public key.

I can see at least 3 ways to do this:

1. Cache is permanent and stays in user home.
2. Cache is temporary in `/tmp` and is attached to its parent Ansible process.
3. Cache is temporary in `/tmp` and time-based, old versions removed.

In general I'm leaning towards the temporary approach, but we can start with simple permanent solution in user home and go from there to develop a good temporary approach. The issue with the temporary approach is that you probably can't tell which Ansible call to lookup plugin is the last in a given Ansible run.

**Comment by markoburcul** [comment]
I've created the Vault caching mechanism which is now part of infra-template repo.

Mechanism for caching:
- Vault lookup plugin will create a cache file under `./ansible/files/cache/vault` with a name `${parent_process_pid}.cache`
- the cache file will be encrypted using the Vault token - which needs to be set in the environment
- entries in the cache file are key:value pairs in JSON object, where keys are path in Vault and values are dictionaries of secrets and their values
- each time a Vault lookup is triggered:
  -  first the cache file will be checked if there is a match for a given path and secret name
  - if there is a match it will be returned
  - if not, we will query the Vault API and store all of the secrets on requested path in the cache and in that way optimize future lookups
- when the playbook is done, callback is issued to clean the `./ansible/files/cache/vault` directory
  - in this way we are covering also the cases when the playbook run was interrupted and the cache file remains on the system(although it will not be used ever again)

**Comment by jakubgs** [comment]
That's a nice writeup. Maybe we could add it in a `README.md` under `ansible/lookup_plugins`.
